manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    # Zephyr çekirdeğini otomatik indirir ve kendi bağımlılıklarını (import) çözer
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 54b57d25e0e
      import: true

  self:
    # Bu projenin workspace (çalışma alanı) içindeki konumunu belirtir
    path: applications/deos_firmware
